from app.models.user import User
from app.models.subject import Subject
from app.models.student import Student
from app.models.timetable import TimetableSlot
from app.models.attendance import Attendance
from app.models.leave import LeaveRequest
from app.models.extra_lecture import ExtraLecture
from app.models.reminder_setting import ReminderSetting
from app.models.marks import StudentMarks
from app.models.notification import Notification
